import { USE_CASES } from './constants'
import { Icon } from '@/components/onboarding/icon'

export function StepWelcome({ useCase, setUseCase }: { useCase: string | null; setUseCase: (id: string) => void }) {
  return (
    <div className="ob-card">
      <div className="ob-left">
        <div className="ob-eyebrow"><span className="pip" /> Step 1 · Welcome</div>
        <h1>Let&apos;s issue your first signed QR.</h1>
        <p className="lede">
          Four quick steps. Under a minute. By the end you&apos;ll have a real signed QR — generated by your account, validated, and ready to drop into your app.
        </p>
        <ul className="ob-bullets">
          <li><span className="icowrap"><Icon name="key" size={14} /></span><span><b>Create an App ID.</b> One per product surface. Gets its own signing key.</span></li>
          <li><span className="icowrap"><Icon name="lock" size={14} /></span><span><b>Save your signing key.</b> Shown once. Never leaves your servers.</span></li>
          <li><span className="icowrap"><Icon name="qr" size={14} /></span><span><b>Sign a payload.</b> Issue your first real signed QR with one request.</span></li>
          <li><span className="icowrap"><Icon name="check-circle" size={14} /></span><span><b>Validate it.</b> A single GET. Returns the decoded payload and expiry.</span></li>
        </ul>
      </div>
      <div className="ob-right">
        <div className="ob-right-head">
          <div className="dots"><span /><span /><span /></div>
          <span className="rh-label">What are you signing?</span>
        </div>
        <div className="ob-right-body">
          <p style={{ margin: '0 0 14px', fontSize: 13, color: 'var(--muted)' }}>
            Just so we can pre-fill your first App. You can change all of this later.
          </p>
          <div className="uc-grid">
            {USE_CASES.map((option) => (
              <button key={option.id} type="button" data-testid={`ob-use-case-${option.id}`} className={`uc-card${useCase === option.id ? ' active' : ''}`} onClick={() => setUseCase(option.id)}>
                <span className="ico"><Icon name={option.icon} size={16} /></span>
                <span>
                  <div className="uc-lbl">{option.label}</div>
                  <div className="uc-sub">{option.sub}</div>
                </span>
              </button>
            ))}
          </div>
        </div>
      </div>
    </div>
  )
}