name: Test

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: supabase/setup-cli@v1
        with:
          version: latest
      
      - name: Start Supabase
        run: supabase start
      
      - name: Supabase Tests
        run: supabase test db
      
      - name: Shutdown Supabase
        run: supabase stop
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Unit Tests
        run: npm test

      - name: Build
        run: npm run build

      - name: E2E Tests
        run: npm run test:e2e